import type { PackingItemRow } from '../types/missing_tables'

/** Offline fallback when DB has no NZ winter packing rows yet */
export const NZ_WINTER_PACKING_FALLBACK: PackingItemRow[] = [
  {
    id: 'nz-w-doc-passport',
    dest: 'New Zealand',
    season: 'winter',
    category: 'documents',
    priority: 'must_have',
    label_en: 'Passport (6+ months validity)',
    label_th: 'พาสปอร์ต (อายุ 6 เดือนขึ้นไป)',
    weather_note_en: 'NZ winter: layers, waterproof jacket, warm hat',
    weather_note_th: 'ฤดูหนาว NZ: ใส่เป็นชั้น ๆ กันหนาว กันฝน',
    sort_order: 1,
  },
  {
    id: 'nz-w-doc-insurance',
    dest: 'New Zealand',
    season: 'winter',
    category: 'documents',
    priority: 'must_have',
    label_en: 'Travel insurance + policy copy',
    label_th: 'ประกันเดินทาง + สำเนากรมธรรม์',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 2,
  },
  {
    id: 'nz-w-cloth-jacket',
    dest: 'New Zealand',
    season: 'winter',
    category: 'clothing',
    priority: 'must_have',
    label_en: 'Waterproof/windproof jacket',
    label_th: 'แจ็กเก็ตกันฝนกันลม',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 1,
  },
  {
    id: 'nz-w-cloth-layers',
    dest: 'New Zealand',
    season: 'winter',
    category: 'clothing',
    priority: 'must_have',
    label_en: 'Thermal base layers (2–3 sets)',
    label_th: 'ชุดชั้นในกันหนาว 2–3 ชุด',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 2,
  },
  {
    id: 'nz-w-cloth-shoes',
    dest: 'New Zealand',
    season: 'winter',
    category: 'clothing',
    priority: 'must_have',
    label_en: 'Comfortable waterproof walking shoes',
    label_th: 'รองเท้าเดินป่ากันฝน',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 3,
  },
  {
    id: 'nz-w-cloth-gloves',
    dest: 'New Zealand',
    season: 'winter',
    category: 'clothing',
    priority: 'nice_to_have',
    label_en: 'Gloves + warm beanie',
    label_th: 'ถุงมือ + หมวกกันหนาว',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 4,
  },
  {
    id: 'nz-w-toilet',
    dest: 'New Zealand',
    season: 'winter',
    category: 'toiletries',
    priority: 'must_have',
    label_en: 'Moisturiser + lip balm (dry winter air)',
    label_th: 'ครีมบำรุงผิว + ลิปบาล์ม',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 1,
  },
  {
    id: 'nz-w-elec-adapter',
    dest: 'New Zealand',
    season: 'winter',
    category: 'electronics',
    priority: 'must_have',
    label_en: 'NZ Type I power adapter',
    label_th: 'ปลั๊กแปลงไฟ Type I (นิวซีแลนด์)',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 1,
  },
  {
    id: 'nz-w-elec-powerbank',
    dest: 'New Zealand',
    season: 'winter',
    category: 'electronics',
    priority: 'nice_to_have',
    label_en: 'Power bank + charging cables',
    label_th: 'พาวเวอร์แบงก์ + สายชาร์จ',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 2,
  },
  {
    id: 'nz-w-health-med',
    dest: 'New Zealand',
    season: 'winter',
    category: 'health',
    priority: 'must_have',
    label_en: 'Personal medications + small first-aid kit',
    label_th: 'ยาประจำตัว + ชุดปฐมพยาบาลเล็ก',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 1,
  },
  {
    id: 'nz-w-other-umbrella',
    dest: 'New Zealand',
    season: 'winter',
    category: 'other',
    priority: 'nice_to_have',
    label_en: 'Compact umbrella / rain cover for bag',
    label_th: 'ร่มพับ / ผ้าคลุมกระเป๋ากันฝน',
    weather_note_en: null,
    weather_note_th: null,
    sort_order: 1,
  },
]
